### ISSUE TITLE
Make a custom blacklist

### ISSUE THREAD

**Issue by SoftwareRat** [jeremehancock/hostminder#1]
Hello,
I really love this software, thank you. I would really love to have an own "blacklist" so I can add my own blocked domains

**Comment by SoftwareRat** [comment]
Or give a option to add own blocklists

**Comment by jeremehancock** [comment]
Thank you very much for your kind words. I am happy that you have found Hostminder to be useful.

There are two ways to add your own set of blocked domains.

If you need to add additional entries simply add them to this section between `# Custom host records are listed here`. and `# End of custom host records.`

The other option would be to contribute directly to [StevenBlack/hosts](https://github.com/StevenBlack/hosts)

One of the goals of this app is to be a simple as possible so I don't want to add too many features.

Thanks again
