### ISSUE TITLE
Why is Fake News only blocked on the maximum protection level?

### ISSUE THREAD

**Issue by Pyroglyph** [jeremehancock/hostminder#5]
With the way the protection levels have been set up, fake news websites are only blocked when using the maximum setting which also blocks social sites.

Why is fake news considered less harmful than social websites? This does not make sense.

I propose a new protection level arrangement:

**Low:** Ads / Porn / Fake News  
**Medium:** Ads / Porn / Fake News / Gambling  
**High:** Ads / Porn / Fake News / Gambling / Social

I feel this new set of protection levels more accurately reflects how harmful each category can be.

**Comment by jeremehancock** [comment]
The Levels are based on the source blocklist used.
https://github.com/StevenBlack/hosts
