### ISSUE TITLE
Add Uninstallation Protection

### ISSUE THREAD

**Issue by baryallen5** [jeremehancock/hostminder#6]
Can someone add Uninstallation Protection in the software, so it is not easily removable and It will require an password
to remove this app from the system. This would make this  a very secure app.

Thanks.

**Comment by jeremehancock** [comment]
The app can't be uninstalled without putting in your `sudo` password like any other app in Ubuntu. To prevent a user from uninstalling you would need to ensure the user doesn't have the ability to uninstall an app on Ubuntu

**Comment by baryallen5** [comment]
> The app can't be uninstalled without putting in your `sudo` password like any other app in Ubuntu. To prevent a user from uninstalling you would need to ensure the user doesn't have the ability to uninstall an app on Ubuntu

Can this have admin level uninstall protection just like [cleanbrowsing client](https://cleanbrowsing.org/help/docs/setup-content-filtering-on-windows-with-cleanbrowsing/) on windows....it cannot be uninstalled without an additional password that the user setup.
